name: Civo CLI

on:
  - pull_request

jobs:
  civo-cli-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install civo
        uses: civo/action-civo@master
        with:
          token: "TODO"
      - name: Install civo
        uses: civo/action-civo@v1.0.1
        with:
          token: "TODO"
